// D-13 / FIX-05 / REND-02/REND-03: the dual-source changelog Content Layer loader. Every build
// merges v1's live changelog.json (auto-generated by v1's own commit skill) with every public row
// of D1's `public_changelogs` table, newest first, and refuses to build rather than ship the
// historical `/changelog` empty-state failure a layer deeper — this is the exact bug this project
// already shipped once in v1 (see 04-08-PLAN.md's own objective).
//
// Unlike articles-loader.ts, this loader has no incremental modes: every build re-fetches both
// sources in full and rebuilds the store from scratch (`store.clear()` + set every entry) — the
// changelog is small (tens of entries, not tens of thousands), so there is no read-budget pressure
// that would justify a windowed/sweep design here.
//
// Every relative import below carries an explicit `.ts` extension — Node 24's native
// type-stripping (used by `node --test` in this project's unit tests, which import this module
// directly) does not resolve extensionless specifiers the way a bundler does.
import type { Loader } from 'astro/loaders';
import { z } from 'astro/zod';
import { queryD1 as queryD1Client } from '../../lib/server/d1-client.ts';
import {
  readLastGood as readLastGoodState,
  writePendingBuildState as writePendingBuildStateFn,
  type LastGoodState,
} from '../../lib/server/build-state.ts';
import { TIME_ZONE } from '../../lib/format.ts';

/** v1's live, auto-generated changelog JSON — fetched at build time rather than vendored, since a
 * committed copy would go stale the moment v1's commit skill writes a new entry
 * (04-08-PLAN.md <planner_findings>). Overridable with `V1_CHANGELOG_URL` — required at Phase 12
 * cutover, when this project's own domain starts serving v2 and this URL must be repointed. */
export const DEFAULT_V1_CHANGELOG_URL = 'https://915tldr.com/changelog.json';

/**
 * Owner-adjusted floor (2026-09-27, 04-08 execution session — see 04-08-SUMMARY.md
 * "Deviations from Plan" for the full writeup).
 *
 * The plan's original value (18) was measured 2026-09-26 against v1's *repo* copy of
 * changelog.json (12 entries) + 6 D1 rows. Re-verified live at execution time (2026-09-27): v1's
 * live changelog.json currently serves only 9 entries, not 12. This is NOT a stale CDN edge
 * cache — `cf-cache-status: HIT` for a static asset with a fresh cache-busting query string is
 * ordinary Workers Static Assets behavior, not evidence of staleness. The real, verified cause
 * (orchestrator, 2026-09-27): v1's last production deployment was 2026-09-19T17:13Z
 * (`wrangler deployments list` in 915tldr.com2), while the 3 missing entries were committed to
 * v1's repo on 2026-09-21 (commit e991d56) and have never been deployed. Production genuinely
 * publishes only 9 JSON entries today, not 12 — this loader reads what v1 actually serves, not
 * its repo's working tree (and never reads v1's repo file or touches v1's Cloudflare zone at
 * build time, by design).
 *
 * Owner decision: floor at what production actually publishes today — 9 JSON + 6 D1 = 15 — not
 * at a count (18) that assumes 3 entries this loader cannot see and must not fetch out-of-band.
 * The never-shrink check below (`lastGood.changelog.count`) ratchets this floor up automatically
 * the first time a build observes a higher total (e.g. 18, once v1 deploys those 3 entries) — no
 * code change needed then; see the "ratchet-up" test in changelog-loader.test.mjs.
 */
export const CHANGELOG_MIN_EXPECTED = 15;

export const changelogSchema = z.object({
  id: z.string().min(1),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'date must be YYYY-MM-DD'),
  title: z.string().min(1),
  items: z.array(z.string().min(1)).min(1),
  source: z.enum(['v1-json', 'd1']),
});

export type ChangelogEntryData = z.infer<typeof changelogSchema>;

interface RawV1Entry {
  date: string;
  title: string;
  items: string[];
}

interface D1ChangelogRow {
  id: number;
  date: number;
  title: string;
  items: string;
}

interface NormalizedEntry {
  id: string;
  date: string;
  title: string;
  items: string[];
  source: 'v1-json' | 'd1';
  originalIndex: number;
}

/** Test seams only — production code never passes any of these; the real defaults are the actual
 * fetch/D1/KV implementations. `fetchJson` deliberately mirrors the global `fetch` signature
 * (raw `Response`-shaped return, not pre-parsed JSON) so the real-build regression replay
 * (`tests/regression/changelog-empty-state.test.mjs`) can point `V1_CHANGELOG_URL` at a `data:`
 * URL and exercise the exact same code path a real network fetch would, with no test-only branch
 * in production code. */
export interface ChangelogLoaderDeps {
  fetchJson?: (url: string) => Promise<Response>;
  queryD1?: () => Promise<D1ChangelogRow[]>;
  readLastGood?: () => Promise<LastGoodState | null>;
  writePending?: (patch: { changelog: { count: number } }) => Promise<void>;
  env?: Record<string, string | undefined>;
}

/** D1's `date` column is epoch seconds (confirmed against the real production row shape — same
 * convention as `articles.published_at`), converted to `YYYY-MM-DD` in America/Denver, never the
 * build machine's own local zone — matches `src/lib/format.ts`'s discipline. `en-CA` is the
 * shortest built-in `Intl` locale that formats numeric dates as `YYYY-MM-DD` directly. */
function epochToDateString(epochSeconds: number): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: TIME_ZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(new Date(epochSeconds * 1000));
  const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((p) => p.type === type)?.value ?? '';
  return `${get('year')}-${get('month')}-${get('day')}`;
}

function dedupeKey(entry: { date: string; title: string; items: string[] }): string {
  return `${entry.date}|${entry.title}|${JSON.stringify(entry.items)}`;
}

export function changelogLoader(deps: ChangelogLoaderDeps = {}): Loader {
  const fetchJson = deps.fetchJson ?? fetch;
  const queryD1 =
    deps.queryD1 ??
    (() =>
      queryD1Client<D1ChangelogRow>(
        'SELECT id, date, title, items FROM public_changelogs WHERE is_public = 1 ORDER BY date DESC'
      ));
  const readLastGood = deps.readLastGood ?? readLastGoodState;
  const writePending = deps.writePending ?? writePendingBuildStateFn;
  const env = deps.env ?? process.env;

  return {
    name: 'd1-changelog',
    schema: changelogSchema,
    load: async ({ store, parseData, generateDigest, logger }) => {
      const url = env.V1_CHANGELOG_URL ?? DEFAULT_V1_CHANGELOG_URL;

      // -----------------------------------------------------------------
      // 1. Fetch + validate the v1 JSON source.
      // -----------------------------------------------------------------
      let response: Response;
      try {
        response = await fetchJson(url);
      } catch (err) {
        throw new Error(`changelog-loader: v1 changelog.json fetch failed: ${(err as Error).message}`);
      }
      if (!response.ok) {
        throw new Error(
          `changelog-loader: v1 changelog.json fetch failed: ${response.status} ${response.statusText}`
        );
      }
      let rawBody: unknown;
      try {
        rawBody = await response.json();
      } catch (err) {
        throw new Error(`changelog-loader: v1 changelog.json is not valid JSON: ${(err as Error).message}`);
      }

      const body = rawBody as { entries?: unknown };
      if (!body || !Array.isArray(body.entries)) {
        throw new Error(
          'changelog-loader: v1 changelog.json has an invalid shape — expected { entries: [...] }'
        );
      }
      const rawEntries = body.entries as RawV1Entry[];
      if (rawEntries.length === 0) {
        throw new Error(
          'changelog-loader: v1 changelog.json has zero entries — refusing to build (the /changelog empty-state failure, REND-03)'
        );
      }

      const jsonEntries: NormalizedEntry[] = rawEntries.map((entry, index) => {
        if (
          typeof entry.date !== 'string' ||
          typeof entry.title !== 'string' ||
          entry.title.length === 0 ||
          !Array.isArray(entry.items) ||
          entry.items.length === 0 ||
          !entry.items.every((item) => typeof item === 'string' && item.length > 0)
        ) {
          throw new Error(`changelog-loader: v1 changelog.json entry at index ${index} has a malformed shape`);
        }
        return {
          id: `json:${entry.date}:${index}`,
          date: entry.date,
          title: entry.title,
          items: entry.items,
          source: 'v1-json',
          originalIndex: index,
        };
      });

      // -----------------------------------------------------------------
      // 2. Fetch + validate the D1 source.
      // -----------------------------------------------------------------
      const d1Rows = await queryD1();
      if (d1Rows.length === 0) {
        throw new Error(
          'changelog-loader: public_changelogs has zero rows — refusing to build (the /changelog empty-state failure, REND-03)'
        );
      }

      const d1Entries: NormalizedEntry[] = d1Rows.map((row, index) => {
        let items: unknown;
        try {
          items = JSON.parse(row.items);
        } catch (err) {
          throw new Error(
            `changelog-loader: public_changelogs row ${row.id} has items that is not valid JSON: ${(err as Error).message}`
          );
        }
        if (
          !Array.isArray(items) ||
          items.length === 0 ||
          !items.every((item) => typeof item === 'string' && item.length > 0)
        ) {
          throw new Error(
            `changelog-loader: public_changelogs row ${row.id} has items that is not a non-empty JSON array of strings`
          );
        }
        return {
          id: `d1:${row.id}`,
          date: epochToDateString(row.date),
          title: row.title,
          items: items as string[],
          source: 'd1',
          originalIndex: index,
        };
      });

      // -----------------------------------------------------------------
      // 3. Merge — exact-duplicate removal only (keep the v1-json copy).
      // -----------------------------------------------------------------
      const jsonKeys = new Set(jsonEntries.map(dedupeKey));
      const dedupedD1Entries = d1Entries.filter((entry) => !jsonKeys.has(dedupeKey(entry)));

      const merged = [...jsonEntries, ...dedupedD1Entries].sort((a, b) => {
        if (a.date !== b.date) return a.date < b.date ? 1 : -1; // date desc
        if (a.source !== b.source) return a.source === 'v1-json' ? -1 : 1; // json before d1
        return a.originalIndex - b.originalIndex;
      });

      // -----------------------------------------------------------------
      // 4. Never-shrink check — before any store mutation.
      // -----------------------------------------------------------------
      const total = merged.length;
      const lastGood = await readLastGood();
      const previousCount = lastGood?.changelog?.count;
      const allowance = parseInt(env.ALLOWED_CHANGELOG_SHRINK ?? '0', 10);

      if (previousCount !== undefined) {
        const floor = previousCount - allowance;
        if (total < floor) {
          throw new Error(
            `changelog-loader: never-shrink check failed — total ${total} is below last-good ${previousCount} minus allowance ${allowance} (floor ${floor})`
          );
        }
      } else if (total < CHANGELOG_MIN_EXPECTED) {
        throw new Error(
          `changelog-loader: total ${total} is below CHANGELOG_MIN_EXPECTED (${CHANGELOG_MIN_EXPECTED}) and no last-good baseline exists yet`
        );
      }

      // -----------------------------------------------------------------
      // 5. Mutate the store — only now.
      // -----------------------------------------------------------------
      store.clear();
      for (const entry of merged) {
        const data = {
          id: entry.id,
          date: entry.date,
          title: entry.title,
          items: entry.items,
          source: entry.source,
        };
        const parsed = (await parseData({ id: entry.id, data })) as ChangelogEntryData;
        const digest = generateDigest(parsed as unknown as Record<string, unknown>);
        store.set({ id: entry.id, data: parsed, digest });
      }

      // -----------------------------------------------------------------
      // 6. Pending build state + summary log line.
      // -----------------------------------------------------------------
      await writePending({ changelog: { count: total } });

      logger.info(`sources=json:${jsonEntries.length},d1:${d1Entries.length} total=${total}`);
    },
  };
}
